# Generated by Django 4.1.4 on 2023-08-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anandu',
            new_name='nandu',
        ),
    ]
