# Generated by Django 4.1.4 on 2023-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_anandu_nandu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(blank=True, null=True)),
                ('phno', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
