# Generated by Django 4.1.4 on 2023-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='nandu',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
